---
title: "Blake Massey - Dissertation"
subtitle: "Bald Eagle IBM" 
author: "Blake Massey"
institute: "RStudio, PBC"
date: "2016/12/12 (updated: `r Sys.Date()`)"
output:
  xaringan::moon_reader:
    lib_dir: libs
    seal: false
    css: ["default", "default-fonts", "xaringan-themer.css", "ninjutsu", 'Assets/CSS/style_scaffold.css']
    nature:
      ratio: 16:9
      highlightStyle: github
      highlightLines: true
      slideNumberFormat: "%current%"
      countIncrementalSlides: true
      navigation:
        scroll: false      
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  comment = '', eval = TRUE, message = TRUE, results = "asis", echo = FALSE,
  include = FALSE)
xaringanExtra::use_xaringan_extra(c("tile_view", "scribble"))
```

```{r xaringan-themer, eval = TRUE}
library(xaringanthemer)
style_xaringan(
  header_font_google = google_font("Lato"),
  #background_color = "#FDF7E9", #gplots::col2hex("whitesmoke"),
  extra_css = list(".remark-slide-scaler" = list("overflow-y" = "auto"),
    ".remark-slide-number" = list("display" = "none")))
```

```{r child = 'Dissertation_02_Title.Rmd', eval = TRUE}
```

```{r child = 'Dissertation_03_Intro.Rmd', eval = FALSE}
```

```{r child = 'Dissertation_04_Ch1.Rmd', eval = FALSE}
```

```{r child = 'Dissertation_05_Ch2.Rmd', eval = FALSE}
```

```{r child = 'Dissertation_06_Ch3.Rmd', eval = FALSE}
```

```{r child = 'Dissertation_07_Ch4.Rmd', eval = TRUE}
```

```{r child = 'Dissertation_08_Conclusion.Rmd', eval = FALSE}
```

